# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geospatial', '0001_initial'),
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=20)),
                ('description_meaning', models.TextField(blank=True)),
                ('description_usage', models.TextField(blank=True)),
                ('description_creation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[(b'change', b'change'), (b'state', b'state')], help_text=b'Type of indicator', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('short_name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wetland',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='geospatial.Region')),
                ('country', models.CharField(max_length=200)),
                ('geo_scale', models.CharField(blank=True, max_length=200)),
                ('size', models.FloatField(blank=True)),
                ('short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('partner', models.CharField(blank=True, max_length=200, null=True)),
                ('site_type', models.CharField(blank=True, max_length=200, null=True)),
                ('ecoregion', models.CharField(blank=True, max_length=200, null=True)),
                ('wetland_type', models.CharField(blank=True, max_length=200, null=True)),
                ('service_case', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('geospatial.region',),
        ),
        migrations.CreateModel(
            name='WetlandLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='layers.Layer')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_indicator', to='swos.Indicator', verbose_name=b'Indicator')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_product', to='swos.Product', verbose_name=b'Product')),
                ('wetland', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_wetland', to='swos.Wetland', verbose_name=b'Wetland')),
            ],
            bases=('layers.layer',),
        ),
        migrations.AddField(
            model_name='product',
            name='wetlands',
            field=models.ManyToManyField(blank=True, related_name='swos_product_wetlands', to='swos.Wetland', verbose_name=b'Wetlands'),
        ),
    ]
