# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationlayer',
            name='legend',
            field=models.CharField(blank=True, choices=[(b'MAES', b'MAES'), (b'CLC', b'CLC'), (b'LCCS', b'LCCS')], max_length=200, null=True, verbose_name=b'Classification legend'),
        ),
    ]
