# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'BingMaps', b'BingMaps'), (b'WMS', b'WMS'), (b'WMTS', b'WMTS'), (b'XYZ', b'XYZ'), (b'MapQuest', b'MapQuest'), (b'OSM', b'OSM')], max_length=10)),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'URL')),
                ('layername', models.CharField(blank=True, max_length=200, null=True)),
                ('imageformat', models.CharField(blank=True, max_length=100, null=True)),
                ('wmts_matrixset', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'WMTS matrix set')),
                ('wmts_resolutions', models.TextField(blank=True, help_text=b'separated by space/blank character', null=True, verbose_name=b'WMTS resolutions')),
                ('wmts_projection', models.IntegerField(blank=True, help_text=b'EPSG code (only number)', null=True, verbose_name=b'WMTS projection')),
                ('wmts_tilesize', models.IntegerField(blank=True, help_text=b'e.g., 256, 512', null=True, verbose_name=b'WMTS tilesize')),
            ],
        ),
        migrations.CreateModel(
            name='BaseLayerInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('baselayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapviewer.BaseLayer')),
            ],
        ),
        migrations.CreateModel(
            name='MapViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('template_file', models.FilePathField(match=b'.*\\.html', path=b'D:/PycharmProjects/geoportal/framework\\templates/mapviewer', verbose_name=b'Template file')),
                ('auth_registration', models.BooleanField(default=False, verbose_name=b'Allow user registration')),
                ('addexternallayer', models.BooleanField(default=False, help_text=b'(Hint: If activated, the button for add external layers to map by users is not hidden.)', verbose_name=b'Allow external layers')),
                ('center_lat', models.FloatField(default=90.0, help_text=b'Center coordinate (latitude)', verbose_name=b'Center latitude')),
                ('center_lon', models.FloatField(default=25.0, help_text=b'Center coordinate (longitude)', verbose_name=b'Center longitude')),
                ('center_proj', models.CharField(default=b'EPSG:4326', help_text=b'EPSG projection code of center coordinate', max_length=15, verbose_name=b'Center projection')),
                ('map_proj', models.CharField(default=b'EPSG:4326', help_text=b'EPSG projection code (e.g. EPSG:3857 - WGS84 Web Mercator, used in many popular web mapping applications (GoogleMaps/OpenStreetMap/etc))', max_length=15, verbose_name=b'Map projection')),
                ('map_resolutions', models.TextField(blank=True, help_text=b'Map resolutions (seperated by space/blank character)', null=True, verbose_name=b'Map zoom resolutions')),
                ('zoom_min', models.IntegerField(default=0, help_text=b'Default: 0', verbose_name=b'Minimum zoom for map')),
                ('zoom_max', models.IntegerField(default=28, help_text=b'(Hint: Please check the max supported zoom level of your used base layer.)', verbose_name=b'Maximum zoom for map')),
                ('zoom_init', models.IntegerField(default=4, help_text=b'Default: 4', verbose_name=b'Initial zoom for map')),
                ('auth_perm', models.BooleanField(default=True, help_text=b'Restrict viewer access', verbose_name=b'Access permission')),
                ('download_perm', models.BooleanField(default=True, verbose_name=b'Download permission')),
                ('time_slider', models.BooleanField(default=False, help_text=b'Activate time slider', verbose_name=b'Time slider')),
                ('time_slider_start', models.DateTimeField(blank=True, null=True, verbose_name=b'Starting date')),
                ('time_slider_end', models.DateTimeField(blank=True, null=True, verbose_name=b'Ending date')),
                ('time_slider_interval', models.CharField(blank=True, choices=[(b'year', b'year'), (b'month', b'month'), (b'week', b'week'), (b'day', b'day')], max_length=100, null=True, verbose_name=b'Step interval')),
                ('time_slider_dates', models.TextField(blank=True, help_text=b'Dates separated by comma', null=True, verbose_name=b'Individual dates')),
                ('html_info', models.TextField(blank=True, help_text=b'Please note: Line breaks will be converted to &lt;br&gt; tags', null=True, verbose_name=b'Info text (HTML)')),
                ('html_footer', models.TextField(blank=True, null=True, verbose_name=b'Footer text (HTML)')),
                ('auth_groups', models.ManyToManyField(blank=True, to='auth.Group', verbose_name=b'Access groups')),
                ('auth_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name=b'Access users')),
                ('download_groups', models.ManyToManyField(blank=True, related_name='download_groups', to='auth.Group')),
                ('download_users', models.ManyToManyField(blank=True, related_name='download_users', to=settings.AUTH_USER_MODEL)),
                ('search_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csw.CSW', verbose_name=b'Server for search field')),
            ],
        ),
    ]
