# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
        ('mapviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerBaseInline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('baselayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layerbase', to='layers.Layer')),
                ('mapviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapviewer.MapViewer')),
            ],
        ),
        migrations.AddField(
            model_name='baselayerinline',
            name='mapviewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mapviewer.MapViewer'),
            preserve_default=False,
        ),
    ]
