# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('phaenopt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenScienceProject',
            fields=[
                ('externaldatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.ExternalDatabase')),
                ('data_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('content.externaldatabase',),
        ),
    ]
