# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaenopt', '0002_citizenscienceproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenscienceproject',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
