# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 09:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phaenopt', '0003_citizenscienceproject_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenScienceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.CharField(max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('properties', models.TextField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_project', to='phaenopt.CitizenScienceProject', verbose_name='Project')),
            ],
        ),
    ]
