# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaenopt', '0004_citizensciencedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizensciencedata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizensciencedata',
            name='name',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizensciencedata',
            name='plant',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizensciencedata',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
