# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaenopt', '0005_auto_20180718_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='DWDStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stations_id', models.IntegerField()),
                ('Stationsname', models.CharField(max_length=200)),
                ('geograph_Breite', models.FloatField()),
                ('geograph_Laenge', models.FloatField()),
                ('Stationshoehe', models.FloatField()),
                ('Naturraumgruppe_Code', models.IntegerField()),
                ('Naturraumgruppe', models.CharField(max_length=200)),
                ('Naturraum_Code', models.IntegerField()),
                ('Naturraum', models.CharField(max_length=200)),
                ('Stationsaufloesung', models.DateField(blank=True, null=True)),
                ('Bundesland', models.CharField(max_length=200)),
            ],
        ),
    ]
