# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phaenopt', '0008_dwdinsitudata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwdinsitudata',
            name='Objekt_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dwdinsitudata',
            name='Phase_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dwdinsitudata',
            name='Stations_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dwdstation',
            name='Stations_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dwdstation',
            name='Stationsaufloesung',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
