# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-14 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
