# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'CSW', b'CSW')], default=b'CSW', max_length=10)),
                ('url', models.CharField(max_length=200, verbose_name=b'URL')),
            ],
            options={
                'verbose_name': 'CSW',
                'verbose_name_plural': 'CSW',
            },
        ),
    ]
